### ISSUE TITLE
Cannot find package.json in root path

### ISSUE THREAD

**Issue by thackerc** [saitho/ng-appversion#14]
I installed ts-appversion in my angular project and ran:
`node ./node_modules/@saithodev/ts-appversion/index.js`
and got the following error:
> [NgAppVersion] Cannot find package.json in root path. Skipping...

Looking in ./node_modules/@saithodev/ts-appversion/index.js I changed line 8 from:
`let rootPath = path.join('..', '..');`
to:
`let rootPath = path.join('..', '..', '..');`

This seemed to fix the error.

**Comment by saitho** [comment]
Thanks for the report. That happened when I changed the package name.
I applied the fix and a new version was released to NPM. ;)
