### ISSUE TITLE
Always getting wrong (and non-existing) git ref

### ISSUE THREAD

**Issue by davidkarlsen** [saitho/ng-appversion#7]
I always get the git ref version `gcfb9f4f` instead of current HEAD:

```
export const version = '2.3.1-SNAPSHOT';
export const versionLong = '2.3.1-SNAPSHOT-gcfb9f4f';
```

but:
```
git log|grep -i gcfb9f4f
[et2448@Davids-Work-MacBook-Pro tac-jfr-js-client (⎈ |icp-global-context:kube-system)]$ 
```

**Comment by saitho** [comment]
ng-appversion uses `git describe`, which appends a "g" as a prefix before the commit hash.
Therefore the commit hash in your example is `cfb9f4f` (just remove the g when looking for the commit)

For more information see https://git-scm.com/docs/git-describe .

**Comment by davidkarlsen** [comment]
Doh - that was a bit n00b of me 🤦‍♂ - thanks!

**Comment by saitho** [comment]
No worries. :) I'm glad my package is helpful ^^
